package com.flaskcompiler.codegen;

import com.flaskcompiler.ast.Node;
import com.flaskcompiler.ast.jinja.TemplateNode;
import com.flaskcompiler.ast.python.FunctionNode;
import com.flaskcompiler.ast.python.ProgramNode;
import com.flaskcompiler.ast.python.RouteNode;
import com.flaskcompiler.transfer.BoundTemplate;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates a runnable Flask project from the compiler artifacts.
 * Files only - never executes Flask, never starts a server, never renders templates.
 */
public class FlaskGenerator {

    private final List<String> files = new ArrayList<>();

    public void generate(Path out, ProgramNode pythonAst, TemplateNode jinjaAst, BoundTemplate bound)
            throws IOException {
        files.clear();
        Files.createDirectories(out.resolve("templates"));
        Files.createDirectories(out.resolve("static"));

        List<String> routeNames = extractRouteNames(pythonAst);
        List<Map<String, Object>> products = productsFrom(bound);

        write(out, "app.py", appPy(products, routeNames));
        write(out, "templates/base.html", BASE);
        write(out, "templates/products.html", PRODUCTS);
        write(out, "templates/add_product.html", ADD);
        write(out, "templates/product_details.html", DETAILS);
        write(out, "templates/delete_product.html", DELETE);
        write(out, "static/style.css", CSS);
        write(out, "README.md", README_MD);
        write(out, "requirements.txt", "Flask>=2.0\n");
    }

    private void write(Path out, String relative, String content) throws IOException {
        Path target = out.resolve(relative);
        Files.createDirectories(target.getParent());
        Files.writeString(target, content);
        files.add(relative);
    }

    /** Print the generated file tree. */
    public void printGeneratedFiles(Path out) {
        System.out.println(out.getFileName() + "/");
        for (String f : files) {
            if (!f.contains("/")) System.out.println("  " + f);
        }
        Map<String, List<String>> dirs = new LinkedHashMap<>();
        for (String f : files) {
            int slash = f.indexOf('/');
            if (slash >= 0) {
                dirs.computeIfAbsent(f.substring(0, slash), k -> new ArrayList<>())
                    .add(f.substring(slash + 1));
            }
        }
        dirs.forEach((dir, children) -> {
            System.out.println("  " + dir + "/");
            for (String child : children) System.out.println("    " + child);
        });
    }

    // ---------- app.py assembly ----------
    private String appPy(List<Map<String, Object>> products, List<String> routeNames) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by flask-compiler\n");
        sb.append("# routes: ").append(String.join(", ", routeNames)).append("\n\n");
        sb.append(APP_HEADER);
        sb.append("products = [\n");
        for (Map<String, Object> p : products) {
            sb.append("    ").append(pyDict(p)).append(",\n");
        }
        sb.append("]\n\n");
        sb.append(ROUTES);
        return sb.toString();
    }

    private String pyDict(Map<String, Object> map) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (Map.Entry<String, Object> e : map.entrySet()) {
            if (!first) sb.append(", ");
            sb.append("\"").append(e.getKey()).append("\": ").append(pyValue(e.getValue()));
            first = false;
        }
        return sb.append("}").toString();
    }

    private String pyValue(Object v) {
        if (v instanceof Integer) return v.toString();
        if (v instanceof String s) return "\"" + s + "\"";
        return "\"" + String.valueOf(v) + "\"";
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> productsFrom(BoundTemplate bound) {
        List<Map<String, Object>> result = new ArrayList<>();
        Object data = (bound != null) ? bound.getContext().get("products") : null;
        if (data instanceof List<?> list) {
            for (Object item : list) {
                if (item instanceof Map<?, ?> map) {
                    Map<String, Object> entry = new LinkedHashMap<>();
                    map.forEach((k, val) -> entry.put(String.valueOf(k), val));
                    result.add(entry);
                }
            }
        }
        if (result.isEmpty()) {
            Map<String, Object> demo = new LinkedHashMap<>();
            demo.put("id", 1);
            demo.put("name", "Sample");
            demo.put("price", 100);
            demo.put("description", "A sample product");
            result.add(demo);
        }
        return result;
    }

    private List<String> extractRouteNames(ProgramNode program) {
        List<String> names = new ArrayList<>();
        if (program == null) return names;
        for (Node child : program.getChildren()) {
            if (child instanceof RouteNode route) {
                names.add(funcName(((FunctionNode) route).getNodeName()));
            }
        }
        return names;
    }

    private static String funcName(String nodeName) {
        int k = nodeName.indexOf("]:");
        String sig = (k >= 0) ? nodeName.substring(k + 2) : nodeName;
        int i = sig.indexOf('(');
        return (i >= 0) ? sig.substring(0, i) : sig;
    }

    // ---------- static content ----------
    private static final String APP_HEADER = """
from flask import Flask, render_template, request, redirect, url_for

app = Flask(__name__)

""";

    private static final String ROUTES = """
@app.route("/")
def display_products():
    return render_template("products.html", products=products)


@app.route("/add", methods=["GET", "POST"])
def add_product():
    if request.method == "POST":
        new_id = len(products) + 1
        products.append({
            "id": new_id,
            "name": request.form.get("name"),
            "price": request.form.get("price"),
            "description": request.form.get("description"),
        })
        return redirect(url_for("display_products"))
    return render_template("add_product.html")


@app.route("/product/<int:product_id>")
def product_details(product_id):
    product = products[product_id]
    return render_template("product_details.html", product=product, product_id=product_id)


@app.route("/delete/<int:product_id>", methods=["GET", "POST"])
def delete_product(product_id):
    product = products[product_id]
    if request.method == "POST":
        products.pop(product_id)
        return redirect(url_for("display_products"))
    return render_template("delete_product.html", product=product, product_id=product_id)


if __name__ == "__main__":
    app.run(debug=True)
""";

    private static final String BASE = """
<!DOCTYPE html>
<html>
<head>
    <title>Product Store</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header class="nav">
        <a href="{{ url_for('display_products') }}">Products</a>
        <a href="{{ url_for('add_product') }}">Add Product</a>
    </header>
    <main class="content">
        {% block content %}{% endblock %}
    </main>
</body>
</html>
""";

    private static final String PRODUCTS = """
{% extends "base.html" %}
{% block content %}
<h2>Products</h2>
<div class="cards">
    {% for product in products %}
    <div class="card">
        <h3>{{ product.name }}</h3>
        <p class="price">{{ product.price }}</p>
        <a href="{{ url_for('product_details', product_id=loop.index0) }}">Details</a>
        <a href="{{ url_for('delete_product', product_id=loop.index0) }}">Delete</a>
    </div>
    {% endfor %}
</div>
{% endblock %}
""";

    private static final String ADD = """
{% extends "base.html" %}
{% block content %}
<h2>Add Product</h2>
<form method="post" action="{{ url_for('add_product') }}">
    <input type="text" name="name" placeholder="Name">
    <input type="text" name="price" placeholder="Price">
    <input type="text" name="description" placeholder="Description">
    <button type="submit">Add</button>
</form>
{% endblock %}
""";

    private static final String DETAILS = """
{% extends "base.html" %}
{% block content %}
<h2>{{ product.name }}</h2>
<p class="price">{{ product.price }}</p>
<p>{{ product.description }}</p>
<a href="{{ url_for('delete_product', product_id=product_id) }}">Delete</a>
<a href="{{ url_for('display_products') }}">Back</a>
{% endblock %}
""";

    private static final String DELETE = """
{% extends "base.html" %}
{% block content %}
<h2>Delete Product</h2>
<p>Are you sure you want to delete {{ product.name }}?</p>
<form method="post" action="{{ url_for('delete_product', product_id=product_id) }}">
    <button type="submit">Confirm Delete</button>
</form>
<a href="{{ url_for('display_products') }}">Cancel</a>
{% endblock %}
""";

    private static final String CSS = """
body { font-family: Arial, sans-serif; margin: 0; color: #333333; }
.nav { background: #2c3e50; padding: 12px; }
.nav a { color: #ffffff; margin-right: 16px; text-decoration: none; }
.content { padding: 20px; }
.cards { display: flex; flex-wrap: wrap; }
.card { border: 1px solid #cccccc; padding: 12px; margin: 8px; width: 220px; }
.card a { margin-right: 10px; }
.price { color: #e74c3c; font-weight: bold; }
form input, form button { display: block; margin: 8px 0; padding: 8px; }
""";

    private static final String README_MD = """
# Generated Flask Project

Generated by **flask-compiler**.

## Run
```bash
pip install -r requirements.txt
python app.py
```
Then open http://127.0.0.1:5000/

## Pages
- `/` display products
- `/add` add product
- `/product/<id>` product details
- `/delete/<id>` delete product
""";
}

