package org.example.visitor;

import org.example.ast.ASTNode;
import org.example.ast.python.*;
import org.example.gen.python.pythonParser;
import org.example.gen.python.pythonParserBaseVisitor;

/**
 * Builds the Python AST from the ANTLR parse tree generated by the
 * pythonParser.g4 currently used by the project.
 */
public class PythonASTBuilder extends pythonParserBaseVisitor<ASTNode> {


    @Override
    public ASTNode visitProgram(pythonParser.ProgramContext ctx) {
        if (ctx == null) {
            return null;
        }

        ModuleNode module = new ModuleNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.StatementContext stmt : ctx.statement()) {
            ASTNode child = visit(stmt);

            if (child != null) {
                module.addStatement(child);
            }
        }

        return module;
    }

    @Override
    public ASTNode visitStatement(pythonParser.StatementContext ctx) {
        if (ctx == null) {
            return null;
        }

        if (ctx.simpleStmt() != null) {
            return visit(ctx.simpleStmt());
        }

        if (ctx.compoundStmt() != null) {
            return visit(ctx.compoundStmt());
        }

        return null;
    }

    @Override
    public ASTNode visitSimpleStmt(pythonParser.SimpleStmtContext ctx) {
        if (ctx == null || ctx.getChildCount() == 0) {
            return null;
        }

        return visit(ctx.getChild(0));
    }

    @Override
    public ASTNode visitCompoundStmt(pythonParser.CompoundStmtContext ctx) {
        if (ctx == null || ctx.getChildCount() == 0) {
            return null;
        }

        return visit(ctx.getChild(0));
    }


    @Override
    public ASTNode visitImportStmt(pythonParser.ImportStmtContext ctx) {
        if (ctx == null) {
            return null;
        }

        ImportNode node = new ImportNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.DottedNameContext dotted : ctx.dottedName()) {
            if (dotted == null) {
                continue;
            }

            node.addModule(new IdentifierNode(
                    dotted.getText(),
                    dotted.getStart().getLine(),
                    dotted.getStart().getCharPositionInLine()
            ));
        }

        return node;
    }

    @Override
    public ASTNode visitFromImportStmt(
            pythonParser.FromImportStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        String module = ctx.dottedName() != null
                ? ctx.dottedName().getText()
                : "";

        FromImportNode node = new FromImportNode(
                module,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.importNames() != null) {

            if (ctx.importNames().STAR() != null) {

                node.addName(new IdentifierNode(
                        "*",
                        ctx.importNames().STAR().getSymbol().getLine(),
                        ctx.importNames().STAR()
                                .getSymbol()
                                .getCharPositionInLine()
                ));

            } else {

                for (pythonParser.ImportNameContext nameCtx
                        : ctx.importNames().importName()) {

                    if (nameCtx != null) {
                        node.addName(new IdentifierNode(
                                nameCtx.getText(),
                                nameCtx.getStart().getLine(),
                                nameCtx.getStart().getCharPositionInLine()
                        ));
                    }
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitAssignStmt(
            pythonParser.AssignStmtContext ctx) {

        if (ctx == null ||
                ctx.target().isEmpty() ||
                ctx.expression() == null) {
            return null;
        }

        ASTNode value = visit(ctx.expression());

        for (int i = ctx.target().size() - 1; i >= 0; i--) {

            ASTNode target = visit(
                    ctx.target().get(i)
            );

            value = new AssignmentNode(
                    target,
                    value,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return value;
    }

    @Override
    public ASTNode visitAugAssignStmt(
            pythonParser.AugAssignStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode target = ctx.target() != null
                ? visit(ctx.target())
                : null;

        ASTNode value = ctx.expression() != null
                ? visit(ctx.expression())
                : null;

        String op = ctx.AUGASSIGN() != null
                ? ctx.AUGASSIGN().getText()
                : "";

        return new AugmentedAssignmentNode(
                target,
                op,
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitTarget(pythonParser.TargetContext ctx) {
        if (ctx == null || ctx.IDENT().isEmpty()) {
            return null;
        }

        ASTNode current = new IdentifierNode(
                ctx.IDENT().get(0).getText(),
                ctx.IDENT().get(0).getSymbol().getLine(),
                ctx.IDENT().get(0).getSymbol().getCharPositionInLine()
        );

        for (int i = 1; i < ctx.getChildCount(); i++) {

            org.antlr.v4.runtime.tree.ParseTree child =
                    ctx.getChild(i);

            if (child instanceof org.antlr.v4.runtime.tree.TerminalNode terminal) {

                String text = terminal.getText();

                if (".".equals(text) &&
                        i + 1 < ctx.getChildCount()) {

                    String attr =
                            ctx.getChild(i + 1).getText();

                    current = new AttributeNode(
                            current,
                            attr,
                            terminal.getSymbol().getLine(),
                            terminal.getSymbol().getCharPositionInLine()
                    );

                    i++;
                }

            } else if (child instanceof pythonParser.ExpressionContext expressionContext) {

                current = new SubscriptNode(
                        current,
                        visit(expressionContext),
                        expressionContext.getStart().getLine(),
                        expressionContext.getStart().getCharPositionInLine()
                );
            }
        }

        return current;
    }

    @Override
    public ASTNode visitReturnStmt(
            pythonParser.ReturnStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode value = ctx.expression() != null
                ? visit(ctx.expression())
                : null;

        return new ReturnNode(
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitDeleteStmt(
            pythonParser.DeleteStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        DeleteNode node = new DeleteNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.TargetContext targetCtx : ctx.target()) {

            ASTNode target = visit(targetCtx);

            if (target != null) {
                node.addTarget(target);
            }
        }

        return node;
    }

    @Override
    public ASTNode visitAssertStmt(
            pythonParser.AssertStmtContext ctx) {

        if (ctx == null || ctx.expression().isEmpty()) {
            return null;
        }

        String condition =
                ctx.expression().get(0).getText();

        String message =
                ctx.expression().size() > 1
                        ? ctx.expression().get(1).getText()
                        : null;

        return new AssertNode(
                condition,
                message,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitGlobalStmt(
            pythonParser.GlobalStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        GlobalNode node = new GlobalNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (org.antlr.v4.runtime.tree.TerminalNode id
                : ctx.IDENT()) {

            node.addName(new IdentifierNode(
                    id.getText(),
                    id.getSymbol().getLine(),
                    id.getSymbol().getCharPositionInLine()
            ));
        }

        return node;
    }

    @Override
    public ASTNode visitNonlocalStmt(
            pythonParser.NonlocalStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        NonlocalNode node = new NonlocalNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (org.antlr.v4.runtime.tree.TerminalNode id
                : ctx.IDENT()) {

            node.addName(new IdentifierNode(
                    id.getText(),
                    id.getSymbol().getLine(),
                    id.getSymbol().getCharPositionInLine()
            ));
        }

        return node;
    }

    @Override
    public ASTNode visitPassStmt(pythonParser.PassStmtContext ctx) {
        if (ctx == null) {
            return null;
        }

        return new PassNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitBreakStmt(pythonParser.BreakStmtContext ctx) {
        if (ctx == null) {
            return null;
        }

        return new BreakNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitContinueStmt(
            pythonParser.ContinueStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        return new ContinueNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitRaiseStmt(
            pythonParser.RaiseStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode exception =
                ctx.expression().size() > 0
                        ? visit(ctx.expression().get(0))
                        : null;

        ASTNode cause =
                ctx.expression().size() > 1
                        ? visit(ctx.expression().get(1))
                        : null;

        return new RaiseNode(
                exception,
                cause,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitYieldStmt(
            pythonParser.YieldStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode value = ctx.expression() != null
                ? visit(ctx.expression())
                : null;

        return new YieldNode(
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }


    @Override
    public ASTNode visitDecoratedDef(
            pythonParser.DecoratedDefContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode definition = null;

        if (ctx.funcDef() != null) {
            definition = visit(ctx.funcDef());

        } else if (ctx.asyncFuncDef() != null) {
            definition = visit(ctx.asyncFuncDef());

        } else if (ctx.classDef() != null) {
            definition = visit(ctx.classDef());
        }

        if (definition == null) {
            return null;
        }

        for (pythonParser.DecoratorContext decoratorCtx
                : ctx.decorator()) {

            ASTNode decorator = visit(decoratorCtx);

            if (decorator != null) {
                definition.addChild(decorator);
            }
        }

        return definition;
    }

    @Override
    public ASTNode visitDecorator(
            pythonParser.DecoratorContext ctx) {

        if (ctx == null) {
            return null;
        }

        DecoratorNode node = new DecoratorNode(
                ctx.dottedName() != null
                        ? ctx.dottedName().getText()
                        : "",
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.argList() != null) {

            for (pythonParser.ArgumentContext arg
                    : ctx.argList().argument()) {

                ASTNode argNode = visit(arg);

                if (argNode != null) {
                    node.addArgument(argNode);
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitFuncDef(
            pythonParser.FuncDefContext ctx) {

        return buildFunction(ctx, false);
    }

    @Override
    public ASTNode visitAsyncFuncDef(
            pythonParser.AsyncFuncDefContext ctx) {

        return buildAsyncFunction(ctx);
    }

    private ASTNode buildFunction(
            pythonParser.FuncDefContext ctx,
            boolean isAsync) {

        if (ctx == null) {
            return null;
        }

        FunctionDefNode node = new FunctionDefNode(
                ctx.IDENT() != null
                        ? ctx.IDENT().getText()
                        : "",
                isAsync,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.paramList() != null) {

            for (pythonParser.ParamContext paramCtx
                    : ctx.paramList().param()) {

                ASTNode param = visit(paramCtx);

                if (param != null) {
                    node.addParameter(param);
                }
            }
        }

        if (ctx.expression() != null) {
            node.setReturnType(
                    visit(ctx.expression())
            );
        }

        addSuiteStatementsToFunction(
                node,
                ctx.suite()
        );

        return node;
    }

    private ASTNode buildAsyncFunction(
            pythonParser.AsyncFuncDefContext ctx) {

        if (ctx == null) {
            return null;
        }

        FunctionDefNode node = new FunctionDefNode(
                ctx.IDENT() != null
                        ? ctx.IDENT().getText()
                        : "",
                true,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.paramList() != null) {

            for (pythonParser.ParamContext paramCtx
                    : ctx.paramList().param()) {

                ASTNode param = visit(paramCtx);

                if (param != null) {
                    node.addParameter(param);
                }
            }
        }

        if (ctx.expression() != null) {
            node.setReturnType(
                    visit(ctx.expression())
            );
        }

        addSuiteStatementsToFunction(
                node,
                ctx.suite()
        );

        return node;
    }

    private void addSuiteStatementsToFunction(
            FunctionDefNode node,
            pythonParser.SuiteContext suite) {

        if (node == null || suite == null) {
            return;
        }

        for (pythonParser.StatementContext stmt
                : suite.statement()) {

            ASTNode child = visit(stmt);

            if (child != null) {
                node.addStatement(child);
            }
        }
    }

    @Override
    public ASTNode visitParam(pythonParser.ParamContext ctx) {
        if (ctx == null) {
            return null;
        }

        String name = ctx.IDENT() != null
                ? ctx.IDENT().getText()
                : ctx.getText();

        return new IdentifierNode(
                name,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }

    @Override
    public ASTNode visitClassDef(
            pythonParser.ClassDefContext ctx) {

        if (ctx == null) {
            return null;
        }

        ClassDefNode node = new ClassDefNode(
                ctx.IDENT() != null
                        ? ctx.IDENT().getText()
                        : "",
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.baseList() != null) {

            for (org.antlr.v4.runtime.tree.TerminalNode base
                    : ctx.baseList().IDENT()) {

                node.addBase(new IdentifierNode(
                        base.getText(),
                        base.getSymbol().getLine(),
                        base.getSymbol().getCharPositionInLine()
                ));
            }
        }

        if (ctx.suite() != null) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addStatement(child);
                }
            }
        }

        return node;
    }


    @Override
    public ASTNode visitIfStmt(pythonParser.IfStmtContext ctx) {

        if (ctx == null ||
                ctx.expression().isEmpty() ||
                ctx.suite().isEmpty()) {

            return null;
        }

        IfNode node = new IfNode(
                visit(ctx.expression().get(0)),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        addStatements(
                node,
                ctx.suite().get(0)
        );

        int conditionCount = ctx.expression().size();
        int suiteIndex = 1;

        for (int i = 1;
             i < conditionCount &&
                     suiteIndex < ctx.suite().size();
             i++, suiteIndex++) {

            pythonParser.ExpressionContext conditionCtx =
                    ctx.expression().get(i);

            ElifNode elifNode = new ElifNode(
                    visit(conditionCtx),
                    conditionCtx.getStart().getLine(),
                    conditionCtx.getStart().getCharPositionInLine()
            );

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(suiteIndex).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    elifNode.addStatement(child);
                }
            }

            node.addElif(elifNode);
        }

        if (ctx.KW_ELSE() != null &&
                suiteIndex < ctx.suite().size()) {

            ElseNode elseNode = new ElseNode(
                    ctx.KW_ELSE().getSymbol().getLine(),
                    ctx.KW_ELSE().getSymbol().getCharPositionInLine()
            );

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(suiteIndex).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    elseNode.addStatement(child);
                }
            }

            node.setElseNode(elseNode);
        }

        return node;
    }

    private void addStatements(
            IfNode node,
            pythonParser.SuiteContext suite) {

        if (node == null || suite == null) {
            return;
        }

        for (pythonParser.StatementContext stmt
                : suite.statement()) {

            ASTNode child = visit(stmt);

            if (child != null) {
                node.addStatement(child);
            }
        }
    }

    @Override
    public ASTNode visitForStmt(
            pythonParser.ForStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        ForNode node = new ForNode(
                ctx.target() != null
                        ? visit(ctx.target())
                        : null,
                ctx.expression() != null
                        ? visit(ctx.expression())
                        : null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (!ctx.suite().isEmpty()) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(0).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addStatement(child);
                }
            }
        }

        if (ctx.KW_ELSE() != null &&
                ctx.suite().size() > 1) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(1).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addElseStatement(child);
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitWhileStmt(
            pythonParser.WhileStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        WhileNode node = new WhileNode(
                ctx.expression() != null
                        ? visit(ctx.expression())
                        : null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (!ctx.suite().isEmpty()) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(0).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addBodyStatement(child);
                }
            }
        }

        if (ctx.KW_ELSE() != null &&
                ctx.suite().size() > 1) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(1).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addElseStatement(child);
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitWithStmt(
            pythonParser.WithStmtContext ctx) {

        if (ctx == null) {
            return null;
        }

        WithNode node = new WithNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.WithItemContext itemCtx
                : ctx.withItem()) {

            ASTNode item = visit(itemCtx);

            if (item != null) {
                node.addItem(item);
            }
        }

        if (ctx.suite() != null) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addBodyStatement(child);
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitWithItem(
            pythonParser.WithItemContext ctx) {

        if (ctx == null || ctx.expression() == null) {
            return null;
        }

        ASTNode expr = visit(ctx.expression());

        if (ctx.target() != null) {

            ASTNode target = visit(ctx.target());

            return new BinaryOpNode(
                    expr,
                    "as",
                    target,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return expr;
    }

    @Override
    public ASTNode visitTryStmt(
            pythonParser.TryStmtContext ctx) {

        if (ctx == null || ctx.suite().isEmpty()) {
            return null;
        }

        TryNode node = new TryNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.StatementContext stmt
                : ctx.suite().get(0).statement()) {

            ASTNode child = visit(stmt);

            if (child != null) {
                node.addBodyStatement(child);
            }
        }

        int suiteIndex = 1;

        for (int i = 0;
             i < ctx.exceptClause().size() &&
                     suiteIndex < ctx.suite().size();
             i++, suiteIndex++) {

            pythonParser.ExceptClauseContext ex =
                    ctx.exceptClause().get(i);

            ASTNode exceptionType =
                    ex.expression() != null &&
                            !ex.expression().isEmpty()
                            ? visit(ex.expression())
                            : null;

            String varName =
                    ex.IDENT() != null
                            ? ex.IDENT().getText()
                            : null;

            ExceptNode handler = new ExceptNode(
                    exceptionType,
                    varName,
                    ex.getStart().getLine(),
                    ex.getStart().getCharPositionInLine()
            );

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(suiteIndex).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    handler.addStatement(child);
                }
            }

            node.addHandler(handler);
        }

        if (ctx.KW_ELSE() != null &&
                suiteIndex < ctx.suite().size()) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(suiteIndex).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addElseStatement(child);
                }
            }

            suiteIndex++;
        }

        if (ctx.KW_FINALLY() != null &&
                suiteIndex < ctx.suite().size()) {

            for (pythonParser.StatementContext stmt
                    : ctx.suite().get(suiteIndex).statement()) {

                ASTNode child = visit(stmt);

                if (child != null) {
                    node.addFinallyStatement(child);
                }
            }
        }

        return node;
    }


    @Override
    public ASTNode visitExpression(
            pythonParser.ExpressionContext ctx) {

        if (ctx == null) {
            return null;
        }

        if (ctx.lambdaExpr() != null) {
            return visit(ctx.lambdaExpr());
        }

        if (ctx.orExpr().size() == 1) {
            return visit(ctx.orExpr().get(0));
        }

        if (ctx.orExpr().size() == 3) {

            ASTNode value =
                    visit(ctx.orExpr().get(0));

            ASTNode condition =
                    visit(ctx.orExpr().get(1));

            ASTNode elseValue =
                    visit(ctx.orExpr().get(2));

            ASTNode conditionPart =
                    new BinaryOpNode(
                            value,
                            "if",
                            condition,
                            ctx.getStart().getLine(),
                            ctx.getStart().getCharPositionInLine()
                    );

            return new BinaryOpNode(
                    conditionPart,
                    "else",
                    elseValue,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return visitChildren(ctx);
    }

    @Override
    public ASTNode visitOrExpr(
            pythonParser.OrExprContext ctx) {

        if (ctx == null || ctx.andExpr().isEmpty()) {
            return null;
        }

        ASTNode left =
                visit(ctx.andExpr().get(0));

        for (int i = 1;
             i < ctx.andExpr().size();
             i++) {

            left = new BinaryOpNode(
                    left,
                    "or",
                    visit(ctx.andExpr().get(i)),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return left;
    }

    @Override
    public ASTNode visitAndExpr(
            pythonParser.AndExprContext ctx) {

        if (ctx == null || ctx.notExpr().isEmpty()) {
            return null;
        }

        ASTNode left =
                visit(ctx.notExpr().get(0));

        for (int i = 1;
             i < ctx.notExpr().size();
             i++) {

            left = new BinaryOpNode(
                    left,
                    "and",
                    visit(ctx.notExpr().get(i)),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return left;
    }

    @Override
    public ASTNode visitNotExpr(
            pythonParser.NotExprContext ctx) {

        if (ctx == null) {
            return null;
        }

        if (ctx.KW_NOT() != null) {

            return new UnaryOpNode(
                    "not",
                    visit(ctx.notExpr()),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return visit(ctx.comparison());
    }

    @Override
    public ASTNode visitComparison(
            pythonParser.ComparisonContext ctx) {

        if (ctx == null || ctx.arith().isEmpty()) {
            return null;
        }

        ASTNode left =
                visit(ctx.arith().get(0));

        for (int i = 0;
             i < ctx.compOp().size();
             i++) {

            left = new BinaryOpNode(
                    left,
                    ctx.compOp().get(i).getText(),
                    visit(ctx.arith().get(i + 1)),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return left;
    }

    @Override
    public ASTNode visitArith(
            pythonParser.ArithContext ctx) {

        if (ctx == null || ctx.term().isEmpty()) {
            return null;
        }

        ASTNode left =
                visit(ctx.term().get(0));

        for (int i = 1;
             i < ctx.term().size();
             i++) {

            left = new BinaryOpNode(
                    left,
                    ctx.getChild(2 * i - 1).getText(),
                    visit(ctx.term().get(i)),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return left;
    }

    @Override
    public ASTNode visitTerm(
            pythonParser.TermContext ctx) {

        if (ctx == null || ctx.factor().isEmpty()) {
            return null;
        }

        ASTNode left =
                visit(ctx.factor().get(0));

        for (int i = 1;
             i < ctx.factor().size();
             i++) {

            left = new BinaryOpNode(
                    left,
                    ctx.getChild(2 * i - 1).getText(),
                    visit(ctx.factor().get(i)),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return left;
    }

    @Override
    public ASTNode visitFactor(
            pythonParser.FactorContext ctx) {

        if (ctx == null) {
            return null;
        }

        if (ctx.factor() != null) {

            return new UnaryOpNode(
                    ctx.getChild(0).getText(),
                    visit(ctx.factor()),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return visit(ctx.power());
    }

    @Override
    public ASTNode visitPower(
            pythonParser.PowerContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode base =
                visit(ctx.awaitExpr());

        if (ctx.factor() != null) {

            return new BinaryOpNode(
                    base,
                    "**",
                    visit(ctx.factor()),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        return base;
    }

    @Override
    public ASTNode visitAwaitExpr(
            pythonParser.AwaitExprContext ctx) {

        if (ctx == null) {
            return null;
        }

        ASTNode base =
                visit(ctx.atom());

        if (ctx.KW_AWAIT() != null) {

            base = new AwaitNode(
                    base,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine()
            );
        }

        for (pythonParser.TrailerContext trailer
                : ctx.trailer()) {

            base = applyTrailer(
                    base,
                    trailer
            );
        }

        return base;
    }

    private ASTNode applyTrailer(
            ASTNode base,
            pythonParser.TrailerContext trailer) {

        if (trailer == null) {
            return base;
        }

        int line =
                trailer.getStart().getLine();

        int col =
                trailer.getStart().getCharPositionInLine();

        if (trailer.DOT() != null &&
                trailer.IDENT() != null) {

            return new AttributeNode(
                    base,
                    trailer.IDENT().getText(),
                    line,
                    col
            );
        }

        if (trailer.LPAREN() != null) {

            CallNode call =
                    new CallNode(
                            base,
                            line,
                            col
                    );

            if (trailer.argList() != null) {

                for (pythonParser.ArgumentContext arg
                        : trailer.argList().argument()) {

                    ASTNode argNode =
                            visit(arg);

                    if (argNode != null) {
                        call.addArgument(argNode);
                    }
                }
            }

            return call;
        }

        if (trailer.LBRACKET() != null &&
                trailer.expression() != null) {

            return new SubscriptNode(
                    base,
                    visit(trailer.expression()),
                    line,
                    col
            );
        }

        return base;
    }


    @Override
    public ASTNode visitAtom(pythonParser.AtomContext ctx) {
        if (ctx == null) {
            return null;
        }

        int line = ctx.getStart().getLine();
        int column = ctx.getStart().getCharPositionInLine();

        if (ctx.IDENT() != null) {
            return new IdentifierNode(
                    ctx.IDENT().getText(),
                    line,
                    column
            );
        }

        if (ctx.NUMBER() != null) {
            return new LiteralNode(
                    "number",
                    ctx.NUMBER().getText(),
                    line,
                    column
            );
        }

        if (!ctx.STRING().isEmpty()) {
            return new LiteralNode(
                    "string",
                    ctx.STRING(0).getText(),
                    line,
                    column
            );
        }

        if (ctx.TRUE() != null) {
            return new LiteralNode(
                    "bool",
                    "True",
                    line,
                    column
            );
        }

        if (ctx.FALSE() != null) {
            return new LiteralNode(
                    "bool",
                    "False",
                    line,
                    column
            );
        }

        if (ctx.NONE() != null) {
            return new LiteralNode(
                    "None",
                    "None",
                    line,
                    column
            );
        }

        if (ctx.ELLIPSIS() != null) {
            return new LiteralNode(
                    "ellipsis",
                    "...",
                    line,
                    column
            );
        }


        if (ctx.LBRACKET() != null) {
            if (ctx.getChildCount() == 2) {
                return new ListNode(line, column);
            }

            return visitChildren(ctx);
        }

        if (ctx.LBRACE() != null) {
            if (ctx.getChildCount() == 2) {
                return new DictNode(line, column);
            }
            return visitChildren(ctx);
        }
        if (ctx.expression() != null) {
            return visit(ctx.expression());
        }
        return null;
    }



    @Override
    public ASTNode visitLiteral(pythonParser.LiteralContext ctx) {
        if (ctx == null) {
            return null;
        }

        ListNode node = new ListNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.ExpressionContext expr : ctx.expression()) {
            ASTNode element = visit(expr);

            if (element != null) {
                node.addElement(element);
            }
        }

        return node;
    }

    @Override
    public ASTNode visitComprehension(
            pythonParser.ComprehensionContext ctx) {

        if (ctx == null) {
            return null;
        }

        ListNode node = new ListNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        ASTNode element = visit(ctx.expression());

        if (element != null) {
            node.addElement(element);
        }

        /*
         * compFor is not added to ListNode because the current
         * ListNode has no dedicated comprehension field.
         */

        return node;
    }

    @Override
    public ASTNode visitDictLiteral(
            pythonParser.DictLiteralContext ctx) {

        if (ctx == null) {
            return null;
        }

        DictNode node = new DictNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        for (pythonParser.DictItemContext item : ctx.dictItem()) {

            ASTNode pair = visit(item);

            if (pair instanceof BinaryOpNode) {
                BinaryOpNode bin = (BinaryOpNode) pair;

                if (":".equals(bin.getOperator())) {
                    node.addPair(
                            bin.getLeft(),
                            bin.getRight()
                    );
                }
            }
        }

        return node;
    }

    @Override
    public ASTNode visitDictComprehension(
            pythonParser.DictComprehensionContext ctx) {

        if (ctx == null) {
            return null;
        }

        DictNode node = new DictNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        ASTNode pair = visit(ctx.dictItem());

        if (pair instanceof BinaryOpNode) {
            BinaryOpNode bin = (BinaryOpNode) pair;

            if (":".equals(bin.getOperator())) {
                node.addPair(
                        bin.getLeft(),
                        bin.getRight()
                );
            }
        }

        /*
         * compFor is not inserted into DictNode because the current
         * DictNode does not contain a dedicated comprehension structure.
         */

        return node;
    }

    @Override
    public ASTNode visitDictItem(
            pythonParser.DictItemContext ctx) {

        if (ctx == null) {
            return null;
        }

        if (ctx.expression().size() < 2) {
            return null;
        }

        ASTNode key = visit(ctx.expression(0));
        ASTNode value = visit(ctx.expression(1));

        return new BinaryOpNode(
                key,
                ":",
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );
    }


    @Override
    public ASTNode visitLambdaExpr(
            pythonParser.LambdaExprContext ctx) {

        if (ctx == null) {
            return null;
        }

        LambdaNode node = new LambdaNode(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine()
        );

        if (ctx.paramList() != null) {

            for (pythonParser.ParamContext param
                    : ctx.paramList().param()) {

                ASTNode parameter =
                        visit(param);

                if (parameter != null) {
                    node.addParameter(parameter);
                }
            }
        }

        if (ctx.expression() != null) {

            node.setBody(
                    visit(ctx.expression())
            );
        }

        return node;
    }

    @Override
    public ASTNode visitArgument(
            pythonParser.ArgumentContext ctx) {

        if (ctx == null) {
            return null;
        }

        if (ctx.expression() != null) {

            ASTNode value =
                    visit(ctx.expression());

            String prefix =
                    ctx.getChildCount() > 0
                            ? ctx.getChild(0).getText()
                            : "";

            if (ctx.IDENT() != null) {

                return new BinaryOpNode(
                        new IdentifierNode(
                                ctx.IDENT().getText(),
                                ctx.IDENT().getSymbol().getLine(),
                                ctx.IDENT()
                                        .getSymbol()
                                        .getCharPositionInLine()
                        ),
                        "=",
                        value,
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine()
                );
            }

            if ("*".equals(prefix) ||
                    "**".equals(prefix)) {

                return new UnaryOpNode(
                        prefix,
                        value,
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine()
                );
            }

            return value;
        }

        return visitChildren(ctx);
    }
}